global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "mqtt"
    metrics_path: /mqtt
    static_configs:
      - targets:
          - diox/+/+
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_topic
      - source_labels: [__param_topic]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9337
    metric_relabel_configs:
      - source_labels: [topic]
        target_label: dev
        regex: diox/(.+)/.+
      - source_labels: [topic]
        target_label: __name__
        regex: diox/.+/(.+)
        replacement: "diox_$1"
      - regex: topic
        action: labeldrop
